	 IDENTIFICATION DIVISION.
	 PROGRAM-ID. PROG1.
	 ENVIRONMENT DIVISION.
	 DATA DIVISION.

	 PROCEDURE DIVISION.
	       
	 PROGRAM-BEGIN.
	    DISPLAY "Hello to Cobol world, Mariane".
      *> comentario. 	
	 PROGRAM-DONE.
	    STOP RUN.
